import { library } from "@fortawesome/fontawesome-svg-core";
import {} from "@fortawesome/free-regular-svg-icons";
import {
  faInstagram,
  faFacebook,
  faTwitter,
} from "@fortawesome/free-brands-svg-icons";
import {
  faAngleDown,
  faShoppingCart,
  faSearch,
  faDashboard,
  faShoppingBasket,
  faUserGroup,
  faHandshakeAngle,
  faList,
  faTrophy,
  faInfo,
  faMoneyBills,
  faCheck,
  faCertificate,
  faPen,
  faAddressBook,
  faEnvelope,
  faPhone,
  faQuoteLeft,
  faGlobe,
  faTrashCan,
  faCirclePlus,
  faArrowLeft,
  faLocationDot,
  faBusinessTime,
  faLink,
  faAdd,
} from "@fortawesome/free-solid-svg-icons";

library.add(
  faShoppingCart,
  faAngleDown,
  faSearch,
  faDashboard,
  faShoppingBasket,
  faUserGroup,
  faHandshakeAngle,
  faList,
  faTrophy,
  faInfo,
  faMoneyBills,
  faCheck,
  faCertificate,
  faPen,
  faAddressBook,
  faEnvelope,
  faPhone,
  faQuoteLeft,
  faGlobe,
  faInstagram,
  faFacebook,
  faTwitter,
  faTrashCan,
  faCirclePlus,
  faArrowLeft,
  faLocationDot,
  faBusinessTime,
  faLink,
  faAdd
);
