import { library } from "@fortawesome/fontawesome-svg-core";
import {} from "@fortawesome/free-regular-svg-icons";
import {
  faInstagram,
  faFacebook,
  faTwitter,
} from "@fortawesome/free-brands-svg-icons";
import {
  faAngleDown,
  faShoppingCart,
  faSearch,
  faDashboard,
  faShoppingBasket,
  faPeopleGroup,
  faHandshakeAngle,
  faList,
  faAward,
  faInfo,
  faMoneyBill,
  faCheck,
  faCertificate,
  faPen,
  faAddressBook,
  faEnvelope,
  faPhone,
  faLocation,
  faExternalLink,
  faQuoteLeft,
  faGlobe,
} from "@fortawesome/free-solid-svg-icons";

library.add(
  faShoppingCart,
  faAngleDown,
  faSearch,
  faDashboard,
  faShoppingBasket,
  faPeopleGroup,
  faHandshakeAngle,
  faList,
  faAward,
  faInfo,
  faMoneyBill,
  faCheck,
  faCertificate,
  faPen,
  faAddressBook,
  faEnvelope,
  faPhone,
  faLocation,
  faExternalLink,
  faQuoteLeft,
  faGlobe,
  faInstagram,
  faFacebook,
  faTwitter
);
